'use strict';

/**
 * Shared config for k6 load-test scenarios (loadtest/).
 *
 * Auth is COOKIE-ONLY (security round 1): k6 sends `Cookie: accessToken=<jwt>`.
 * JWTs are PRE-GENERATED by scripts/seedLoadTestCohort.js — login is measured
 * by its own surge scenario, never inside the browsing mix.
 *
 * Concurrency model (plan §"the single most important correction"):
 * 10k *online* users ≠ 10k requests in flight. A student acts every ~5–15s and
 * one action = 1–4 API calls. With ~10s mean think time inside each iteration,
 * an arrival rate of U/10 iterations/sec models U online users, and the VU pool
 * (arrival rate × iteration duration) reproduces the simultaneous-herd effect.
 */

const BASE_URL = __ENV.BASE_URL || 'http://localhost:3005';

// SLO table (plan Phase 1). 429s are counted as errors on purpose — under the
// LOAD_TEST profile the ceilings are raised, so a 429 means the profile is off
// or the ceiling is genuinely too low: both are findings, not noise.
const SLO = {
  'http_req_failed': ['rate<0.01'],
  'http_req_duration': ['p(95)<1000'],
  'http_req_duration{kind:gate}': ['p(95)<2000'],
  'http_req_duration{kind:login}': ['p(95)<3000'],
  checks: ['rate>0.99'],
};

// Full ramp: target = iterations/sec = online_users / 10.
// 10 → 100 online (L1), 50 → 500 (L2a), 120 → 1.2k (L2b), 300 → 3k (L3),
// 600 → 6k (L4a), 1000 → 10k (L4b), hold, drain.
const STAGES_10K = [
  { duration: '2m', target: 10 },
  { duration: '3m', target: 50 },
  { duration: '5m', target: 120 },
  { duration: '5m', target: 300 },
  { duration: '8m', target: 600 },
  { duration: '8m', target: 1000 },
  { duration: '5m', target: 1000 },
  { duration: '3m', target: 0 },
];

/**
 * stagesFor(cap) — truncate STAGES_10K at the first stage whose target exceeds
 * `cap` (that stage IS included), so a baseline run can stop at L1/L2 without
 * editing the ramp:
 *   k6 run -e STAGE_CAP=10   → L0/L1 (100 online)
 *   k6 run -e STAGE_CAP=50   → up to L2a (500 online)
 *   k6 run -e STAGE_CAP=120  → up to L2b (1.2k online)
 *   (omit STAGE_CAP)         → full L0–L4 ramp to 10k online
 */
function stagesFor(cap) {
  if (!Number.isSafeInteger(cap) || cap <= 0) return STAGES_10K;
  const out = [];
  for (const s of STAGES_10K) {
    out.push(s.target > cap ? { duration: s.duration, target: cap } : s);
    if (s.target >= cap) { out.push({ duration: '1m', target: 0 }); return out; }
  }
  return STAGES_10K;
}

// Halt criteria between stages (plan Phase 3): abort the run when p95 doubles
// the stage gate or 5xx exceeds 1% — k6 thresholds make the run FAIL, and the
// runner inspects the per-stage summary before continuing manually.
//
// GENERATOR CEILING (measured on this 8GB box, 2026-09-21): each k6 VU is an
// isolated JS runtime (~1-2MB + shared bundle). 2000 preAllocated VUs OOM'd
// (errno 1455) during init. Budget right-sized: ~200 warm VUs, max 1500 →
// sustainable ≈ 1500 VUs / ~12s iteration ≈ ~125 arrivals/s ≈ ~1.2k online
// users / ~2.5-4k req/s on THIS machine. Targets above that (L3 3k / L4 10k
// online) become generator-bound: k6 reports dropped_iterations — that is a
// load-generator finding for the report, not an app failure. 10k-fidelity
// needs a second generator machine or k6 Cloud (deferred: zero-cost policy).
const VU_BUDGET = { preAllocatedVUs: 200, maxVUs: 1500 };

module.exports = { BASE_URL, SLO, STAGES_10K, VU_BUDGET, stagesFor };