version: '3.8'

services:
  app:
    build: .
    ports:
      - "3005:3005"
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/elearning
      - JWT_SECRET=your_jwt_secret_key
      - NODE_ENV=production
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=elearning
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local