const mux = require('../lib/mux');
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

/**
 * Create a direct upload URL for video upload to Mux
 * This allows admins to upload videos directly to Mux without going through our server
 */
exports.createDirectUpload = async (req, res) => {
  try {
    const { courseId, title, description } = req.body;

    // Validate required fields
    if (!courseId || !title) {
      return res.status(400).json({ 
        error: 'Course ID and title are required' 
      });
    }

    // Verify course exists and user has access
    const course = await prisma.course.findUnique({
      where: { id: parseInt(courseId) }
    });

    if (!course) {
      return res.status(404).json({ error: 'Course not found' });
    }

    // Import mux config
    const muxConfig = require('../config/muxConfig');
    
    // Create direct upload with Mux <mcreference link="https://www.mux.com/video-for/node" index="2">2</mcreference>
    const uploadOptions = {
      ...muxConfig.uploads.defaultDirectUploadOptions,
      new_asset_settings: {
        ...muxConfig.uploads.defaultDirectUploadOptions.new_asset_settings,
        playback_policy: ['signed'], // Use signed URLs for security
        encoding_tier: 'baseline', // Good quality for e-learning
        normalize_audio: true // Normalize audio levels
      },
      timeout: 3600 // 1 hour timeout
    };
    
    const upload = await mux.video.uploads.create(uploadOptions);

    // Create video record in database
    const video = await prisma.video.create({
      data: {
        title,
        description: description || '',
        url: '', // Will be updated when asset is ready
        thumbnail: '', // Will be generated by Mux
        courseId: parseInt(courseId),
        duration: 0, // Will be updated when asset is ready
        isYoutube: false,
        muxData: {
          create: {
            assetId: upload.asset_id,
            uploadId: upload.id,
            status: 'PREPARING'
          }
        }
      },
      include: {
        muxData: true
      }
    });

    res.status(201).json({
      success: true,
      data: {
        uploadUrl: upload.url,
        videoId: video.id,
        assetId: upload.asset_id,
        uploadId: upload.id
      }
    });

  } catch (error) {
    console.error('Error creating direct upload:', error);
    res.status(500).json({ 
      error: 'Failed to create upload URL',
      details: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};

/**
 * Get video streaming URL with signed token for secure access
 */
exports.getStreamingUrl = async (req, res) => {
  try {
    const { videoId } = req.params;
    const userId = req.user.id;

    // Get video with Mux data
    const video = await prisma.video.findUnique({
      where: { id: parseInt(videoId) },
      include: {
        muxData: true,
        course: {
          include: {
            enrollments: {
              where: { userId }
            }
          }
        }
      }
    });

    if (!video) {
      return res.status(404).json({ error: 'Video not found' });
    }

    // Check if user has access to the video
    const hasAccess = req.user.role === 'ADMIN' || 
                     video.course.enrollments.length > 0 ||
                     video.course.price === 0; // Free course

    if (!hasAccess) {
      return res.status(403).json({ error: 'Access denied' });
    }

    // Check if Mux asset is ready
    if (!video.muxData || video.muxData.status !== 'READY' || !video.muxData.playbackId) {
      return res.status(400).json({ 
        error: 'Video is not ready for streaming',
        status: video.muxData?.status || 'UNKNOWN'
      });
    }

    // Generate signed playback URL <mcreference link="https://www.npmjs.com/package/@mux/mux-node" index="5">5</mcreference>
    const playbackToken = mux.jwt.signPlaybackId(video.muxData.playbackId, {
      type: 'video',
      expiration: '24h' // Token valid for 24 hours
    });

    // Generate thumbnail token
    const thumbnailToken = mux.jwt.signPlaybackId(video.muxData.playbackId, {
      type: 'thumbnail',
      expiration: '24h'
    });

    // Generate storyboard token for video scrubbing
    const storyboardToken = mux.jwt.signPlaybackId(video.muxData.playbackId, {
      type: 'storyboard',
      expiration: '24h'
    });

    res.json({
      success: true,
      data: {
        playbackUrl: `https://stream.mux.com/${video.muxData.playbackId}.m3u8?token=${playbackToken}`,
        thumbnailUrl: `https://image.mux.com/${video.muxData.playbackId}/thumbnail.jpg?token=${thumbnailToken}`,
        storyboardUrl: `https://image.mux.com/${video.muxData.playbackId}/storyboard.vtt?token=${storyboardToken}`,
        duration: video.muxData.duration,
        aspectRatio: video.muxData.aspectRatio,
        resolution: video.muxData.resolution
      }
    });

  } catch (error) {
    console.error('Error getting streaming URL:', error);
    res.status(500).json({ 
      error: 'Failed to get streaming URL',
      details: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};

/**
 * Get video asset information
 */
exports.getAssetInfo = async (req, res) => {
  try {
    const { videoId } = req.params;

    const video = await prisma.video.findUnique({
      where: { id: parseInt(videoId) },
      include: {
        muxData: true
      }
    });

    if (!video || !video.muxData) {
      return res.status(404).json({ error: 'Video or Mux data not found' });
    }

    // Get asset details from Mux
    const asset = await mux.video.assets.retrieve(video.muxData.assetId);

    res.json({
      success: true,
      data: {
        assetId: asset.id,
        status: asset.status,
        duration: asset.duration,
        aspectRatio: asset.aspect_ratio,
        resolution: asset.resolution_tier,
        createdAt: asset.created_at,
        tracks: asset.tracks,
        playbackIds: asset.playback_ids
      }
    });

  } catch (error) {
    console.error('Error getting asset info:', error);
    res.status(500).json({ 
      error: 'Failed to get asset information',
      details: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};

/**
 * Delete video asset from Mux
 */
exports.deleteAsset = async (req, res) => {
  try {
    const { videoId } = req.params;

    const video = await prisma.video.findUnique({
      where: { id: parseInt(videoId) },
      include: {
        muxData: true
      }
    });

    if (!video || !video.muxData) {
      return res.status(404).json({ error: 'Video or Mux data not found' });
    }

    // Delete asset from Mux
    await mux.video.assets.delete(video.muxData.assetId);

    // Update database
    await prisma.muxData.update({
      where: { id: video.muxData.id },
      data: {
        status: 'DELETED'
      }
    });

    res.json({
      success: true,
      message: 'Video asset deleted successfully'
    });

  } catch (error) {
    console.error('Error deleting asset:', error);
    res.status(500).json({ 
      error: 'Failed to delete asset',
      details: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};

/**
 * Handle Mux webhooks for asset status updates
 */
exports.handleMuxWebhook = async (req, res) => {
  const muxConfig = require('../config/muxConfig');
  const { webhookSecret } = muxConfig.credentials;

  if (!webhookSecret) {
    console.error('Mux webhook secret not configured');
    return res.status(500).send('Internal Server Error');
  }

  const signature = req.headers['mux-signature'];
  if (!signature) {
    return res.status(401).send('Unauthorized');
  }

  try {
    // Verify webhook signature <mcreference link="https://muxinc.github.io/mux-node-sdk/" index="3">3</mcreference>
    const event = mux.webhooks.verifyHeader(JSON.stringify(req.body), signature, webhookSecret);

    console.log('Received Mux webhook:', event.type, event.data.id);

    // Check if this is a supported event type
    const { supportedEvents } = muxConfig.webhooks;
    if (!supportedEvents.includes(event.type)) {
      console.log('Unhandled webhook event type:', event.type);
      return res.status(200).send('Event type not handled');
    }
    
    // Process the event based on its type
    switch (event.type) {
      case 'video.asset.ready':
        await handleAssetReady(event.data);
        break;
      
      case 'video.asset.errored':
        await handleAssetErrored(event.data);
        break;
      
      case 'video.asset.deleted':
        await handleAssetDeleted(event.data);
        break;
      
      case 'video.upload.asset_created':
        await handleUploadAssetCreated(event.data);
        break;
      
      default:
        console.log('Unhandled webhook event type:', event.type);
    }

    res.status(200).send('OK');
  } catch (err) {
    console.error('Webhook signature verification failed:', err);
    return res.status(400).send('Invalid signature');
  }
};

/**
 * Handle video.asset.ready webhook
 */
exports.handleAssetReady = async function handleAssetReady(data) {
  try {
    const { id, playback_ids, duration, aspect_ratio, resolution_tier, tracks } = data;

    await prisma.muxData.update({
      where: { assetId: id },
      data: {
        playbackId: playback_ids[0]?.id,
        isProcessed: true,
        status: 'READY',
        duration: duration || null,
        aspectRatio: aspect_ratio || null,
        resolution: resolution_tier || null,
        muxUpdatedAt: new Date()
      }
    });

    // Update video duration in the main video record
    if (duration) {
      const muxData = await prisma.muxData.findUnique({
        where: { assetId: id },
        include: { video: true }
      });

      if (muxData) {
        await prisma.video.update({
          where: { id: muxData.videoId },
          data: { duration: Math.round(duration) }
        });
      }
    }

    console.log('Asset ready processed:', id);
  } catch (error) {
    console.error('Error handling asset ready:', error);
  }
}

/**
 * Handle video.asset.errored webhook
 */
exports.handleAssetErrored = async function handleAssetErrored(data) {
  try {
    const { id, errors } = data;

    await prisma.muxData.update({
      where: { assetId: id },
      data: {
        status: 'ERRORED',
        errorMessage: errors ? JSON.stringify(errors) : 'Unknown error',
        muxUpdatedAt: new Date()
      }
    });

    console.log('Asset errored processed:', id);
  } catch (error) {
    console.error('Error handling asset errored:', error);
  }
}

/**
 * Handle video.asset.deleted webhook
 */
exports.handleAssetDeleted = async function handleAssetDeleted(data) {
  try {
    const { id } = data;

    await prisma.muxData.update({
      where: { assetId: id },
      data: {
        status: 'DELETED',
        muxUpdatedAt: new Date()
      }
    });

    console.log('Asset deleted processed:', id);
  } catch (error) {
    console.error('Error handling asset deleted:', error);
  }
}

/**
 * Handle video.upload.asset_created webhook
 */
exports.handleUploadAssetCreated = async function handleUploadAssetCreated(data) {
  try {
    const { id, asset_id } = data;

    await prisma.muxData.update({
      where: { uploadId: id },
      data: {
        assetId: asset_id,
        muxCreatedAt: new Date()
      }
    });

    console.log('Upload asset created processed:', id, asset_id);
  } catch (error) {
    console.error('Error handling upload asset created:', error);
  }
}